[package]
name = "tinff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tinkoff-invest-api = { version = "0.2.3" }
async-stream = "0.3"
futures = {version = "0.3", default-features = false, features = ["alloc"]}
tokio = {version = "1.0", features = ["full"]}
tokio-stream = {version = "0.1", features = ["net"]}
futures-util = {version = "0.3.28"}
rust_decimal = "1.29.1"
prettytable-rs = "0.10.0"
iso_currency = "0.4.3"
itertools = "0.11.0"